global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'kafka-jmx'
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: [ 'jmx_exporter:5556' ]

  - job_name: 'filtering-service'
    static_configs:
      - targets: [ 'filtering_service:8081' ]

  - job_name: 'dedup-service'
    static_configs:
      - targets: [ 'dedup_service:8082' ]

  - job_name: 'enrichment-service'
    static_configs:
      - targets: [ 'enrichment_service:8083' ]

  - job_name: 'management-service'
    static_configs:
      - targets: [ 'management_service:8084' ]
